name: Cleanup Expired Bookings

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub
  schedule:
    - cron: "0 6 * * *" # Se ejecuta todos los días a las 03:00 hora Argentina (UTC-3)

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descarga el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
      - name: Run cleanup script
        run: |
          curl -X POST "https://resio.vercel.app/api/cleanup-bookings" \
            -H "Authorization: Bearer $CLEANUP_API_KEY" \
            -H "Content-Type: application/json" \
            --fail
        env:
          CLEANUP_API_KEY: ${{ secrets.CLEANUP_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
